version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "5050:80"
    volumes:
    - ${PWD}/docker/pgadmin/rootfs/etc/pgadmin/:/etc/pgadmin/
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: pleaseletmein
      PGADMIN_SERVER_JSON_FILE: /etc/pgadmin/pgservers.json
  gabi-proxy:
    build: .
    environment:
      GABI_DOMAIN: ${GABI_DOMAIN}
